name: club_app_admin
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  #region utils:
  connectivity_plus: ^2.3.9
  equatable: ^2.0.5
  font_awesome_flutter: ^10.2.1
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  uuid: ^3.0.7
  #endregion

  #region State Management:
  provider: ^6.0.4
  #endregion

  #region offline database:
  hive: ^2.2.3
  sqflite: ^2.0.3+1
  #endregion

  #region UI:
  cached_network_image: ^3.2.1
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.2
  material_design_icons_flutter: ^6.0.7096

  #region Loaders:
  flutter_spinkit: ^5.1.0
  loading_animation_widget: ^1.2.0+3
  shimmer: ^2.0.0
  #endregion

  #region Popup Messages
  fluttertoast: ^8.1.1
  top_snackbar_flutter: ^3.0.0
  overlay_support: ^2.1.0
  #endregion

  #endregion

  #region Firebase:
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.1.1
  #endregion

  #region Api Operations:
  http: ^0.13.5
  #endregion

  club_model:
    git:
      url: https://github.com/patelmeet341993/club_model
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true