name: club_app_admin
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  club_model:
    git:
      url: https://github.com/patelmeet341993/club_model
      ref: viren
  firebase_storage: ^11.2.2
  image_picker: ^0.8.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/extra/
    - assets/lotties/